version: 0.0
os: linux
files:
  - source: /src
    destination: /opt/cms
  - source: /venv
    destination: /opt/cms_venv
hooks:
  AfterInstall:
    - location: deploy/run-setup.sh
      timeout: 600
  ApplicationStart:
    - location: deploy/restart.sh
      timeout: 60

