version: 0.2

phases:
  build:
    commands:
      - mkdir -p /opt/cms_venv
      - if [ -e /opt/cms_venv.cache ]; then shasum -c /opt/cms_venv.cache || rm -rf /opt/cms_venv /opt/cms_venv.cache; fi
      - if [ ! -e /opt/cms_venv.cache ]; then mkdir -p /opt/cms_venv; fi
      - chmod +x ./deploy/*.sh
      - ./deploy/chmod.sh
      - ./deploy/install-deps.sh
      - shasum requirements.txt > /opt/cms_venv.cache
      - mkdir -p /out/
      - cp appspec.yml /out/
      - cp -av . /out/src
      - cp -av /opt/cms_venv/ /out/venv
      - mkdir -p /out/src/ioi/flags
      - aws s3 sync s3://ioi18-misc/flags /out/src/ioi/flags
      - touch /out/venv/.built-on-codebuild
      
artifacts:
  files:
    - '**/*'
  base-directory: '/out'

cache:
  paths:
    - '/opt/cms_venv.cache'
    - '/opt/cms_venv/**/*'
